server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider-forLinux
  cloud:
    nacos:
      discovery:
        server-addr:  192.168.136.200:1111
      #server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include= *: