server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #客户端注册进eureka服务类表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      fetch-registry: true
      register-with-eureka: true
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2            #路由id
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供的路由地址
          predicates:
            - Path=/payment/lb/**     #断言，路径相匹配的进行路由
            - After=2020-08-11T21:58:59.679+08:00[Asia/Shanghai]
      discovery:
        locator:
          enabled: true

