server:
  port: 83
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: nacos-order-consumer

#消费之将要去访问的微服务名称
service-url:
  nacos-user-service: http://nacos-payment-provider